import { Job, JobDetail } from "./types";

export const mockJobs: Job[] = [
  {
    id: "1",
    title: "Senior Software Engineer",
    department: "Технологийн алба",
    postedDate: "1-р сарын 10",
    salaryMin: 4000000,
    salaryMax: 6000000,
    referralCount: 3,
  },
  {
    id: "2",
    title: "Product Manager",
    department: "Бүтээгдэхүүний алба",
    postedDate: "1-р сарын 8",
    salaryMin: 3500000,
    salaryMax: 5000000,
    referralCount: 1,
  },
  {
    id: "3",
    title: "UX Designer",
    department: "Дизайны алба",
    postedDate: "1-р сарын 5",
    salaryMin: 2500000,
    salaryMax: 4000000,
  },
  {
    id: "4",
    title: "Data Analyst",
    department: "Өгөгдлийн алба",
    postedDate: "1-р сарын 3",
    salaryMin: 3000000,
    salaryMax: 4500000,
  },
];

export const mockJobData: Record<string, JobDetail> = {
  "1": {
    id: "1",
    title: "Senior Software Engineer",
    department: "Технологийн алба",
    jobType: "Бүтэн цагийн",
    level: "Senior",
    salaryMin: 4000000,
    salaryMax: 6000000,
    responsibilities:
      "• Системийн архитектур зохион бүтээх\n• Кодын чанарыг хангах\n• Багийн гишүүдийг удирдах",
    requirements:
      "• 5+ жилийн туршлага\n• React, TypeScript мэдлэг\n• Багаар ажиллах чадвар",
    additionalInfo: "Алсын зайнаас ажиллах боломжтой",
    skills: "React, TypeScript, Node.js, PostgreSQL",
    benefits: "• Эрүүл мэндийн даатгал\n• Амралтын өдрүүд\n• Сургалтын дэмжлэг",
    contactInfo: "hr@company.mn / 7777-7777",
    location: "Улаанбаатар хот, Сүхбаатар дүүрэг",
    postedDate: "1-р сарын 10",
    hasReferrals: true,
  },
  "2": {
    id: "2",
    title: "Product Manager",
    department: "Бүтээгдэхүүний алба",
    jobType: "Бүтэн цагийн",
    level: "Mid-level",
    salaryMin: 3500000,
    salaryMax: 5000000,
    responsibilities:
      "• Бүтээгдэхүүний стратеги боловсруулах\n• Багуудын хооронд уялдаа холбоо хангах",
    requirements: "• 3+ жилийн туршлага\n• Ажайл аргачлалын мэдлэг",
    additionalInfo: "Хосолсон горим боломжтой",
    skills: "Product Management, Agile, Data Analysis",
    benefits: "• Уян хатан цагийн хуваарь\n• Сургалтын дэмжлэг",
    contactInfo: "hr@company.mn / 8888-8888",
    location: "Улаанбаатар хот",
    postedDate: "1-р сарын 8",
    hasReferrals: true,
  },
  "3": {
    id: "3",
    title: "UX Designer",
    department: "Дизайны алба",
    jobType: "Бүтэн цагийн",
    level: "Mid-level",
    salaryMin: 2500000,
    salaryMax: 4000000,
    responsibilities:
      "• Хэрэглэгчийн туршлагын судалгаа\n• UI дизайн боловсруулах",
    requirements: "• 2+ жилийн туршлага\n• Figma, Adobe XD мэдлэг",
    additionalInfo: "Уян хатан цагийн хуваарьтай",
    skills: "Figma, Adobe XD, User Research, Prototyping",
    benefits: "• Уян хатан цаг\n• Дизайн хэрэгслийн дэмжлэг",
    contactInfo: "design@company.mn",
    location: "Улаанбаатар хот",
    postedDate: "1-р сарын 5",
    hasReferrals: false,
  },
  "4": {
    id: "4",
    title: "Data Analyst",
    department: "Өгөгдлийн алба",
    jobType: "Бүтэн цагийн",
    level: "Mid-level",
    salaryMin: 3000000,
    salaryMax: 4500000,
    responsibilities:
      "• Өгөгдлийн шинжилгээ хийх\n• Тайлан бэлтгэх\n• Дата визуалайз хийх",
    requirements:
      "• 2+ жилийн туршлага\n• SQL, Python мэдлэг\n• Статистикийн суурь мэдлэг",
    additionalInfo: "Хосолсон горим",
    skills: "SQL, Python, Tableau, Excel",
    benefits: "• Эрүүл мэндийн даатгал\n• Сургалтын дэмжлэг",
    contactInfo: "hr@company.mn",
    location: "Улаанбаатар хот",
    postedDate: "1-р сарын 3",
    hasReferrals: false,
  },
};
